### ISSUE TITLE
Think about current metadata organization (modularized/cross-referencing)

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#4]
Current structure works; this is just a call for discussion.

## Current structure

There are multiple levels of cross-referencing.

- Block metadata links to various metadata files in different categories (experiment, stimulus, device); 
- then
    - device metadata links to the probe metadata;
    - stimulus metadata to stimulus_value files.

Pro: good modularization. The same experimental setup can be repeated in multiple sessions/blocks.
Con: we don't have a single file that contains all information.

### For example, the content of metadata_path/yaml/block/R56_B10.yaml:

```yaml
name: R56_B10
experiment: nse_aud
device: E128_P64
stimulus: tone
<---other fields--->
```

This means we should read
- metadata_path/yaml/experiment/nse_aud.yaml,
- metadata_path/yaml/device/E128_P64.yaml, and
- metadata_path/yaml/stimulus/tone.yaml.

### Then, the content of device/E128_P64.yaml:

```yaml
name: E128_P64
ECoG: ecog128_6k
Poly: poly64
<---other fields--->
```

This means we should read 
- metadata_path/yaml/probe/ecog128_6k.yaml, and
- metadata_path/yaml/probe/poly64.yaml.

These files contain the full channel coordinates within the probe, among other information.

### Also, the content of stimulus/tone.yaml:

```yaml
name: tone
stim_values: tone_stimulus_values(Tone.stimVls.mat)
<---other fields--->
```

That means we should read Tone.stimVls.mat. This is currently done by StimValueExtractor, but we could improve.
