### ISSUE TITLE
add/rename fields in list_of_stimuli.yaml

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#44]
Currently, the file `list_of_stimuli.yaml` [[link to file]](https://github.com/BouchardLab/nsds_lab_to_nwb/blob/main/nsds_lab_to_nwb/_data/list_of_stimuli.yaml) looks like:

```yaml
# list of known stimuli
# each stimulus entry should have the following structure:
# ———————————————————————————————
# stim_name:
#   alt_names: [list of strings, where each string is an alternative name]
#   description: 'optional string'
#   file: 'wav file path relative to stim_lib_path'
# ———————————————————————————————

tone150:
    alt_names: []
    description: ''
    file: 'Tone150/freq_resp_area_stimulus_signal_flo500Hz_fhi32000Hz_nfreq30_natten1_nreps150_fs96000.wav'

...
```

Suggested changes to make:

- rename `file` to `audio_path`, and add field `marker_path` —  i.e., have separate audio and marker paths (input from @jthermiz @vngutierrez )
    - note: if we do this, also update WavManager accordingly, such that it looks for the correct key name.
- store the name of the .mat file or whatever it is that has the extracted stimulus info like tone, amplitude, etc? (input from @JesseLivezey )
- also add any new stimuli
