### ISSUE TITLE
check, and possibly drop, legacy contents in stimulus metadata

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#54]
I know this is legacy stuff. I don't think it's useful information so maybe get rid off it's not being used for anything?
  stim_values: np.ones(60)
  baseline_start: 0.3
  baseline_end: 0.5
  first_mark: 0.0
  luigi_cls: WhiteNoiseAnalysis
  tokenizer: wn_tokenize

_Originally posted by @jthermiz in https://github.com/BouchardLab/nsds_lab_to_nwb/issues/46#issuecomment-859986965_

**Comment by jihyunbak** [comment]
@VBaratham Which of the fields in the stimulus metadata (file in [this folder in the metadata repo](https://github.com/BouchardLab/NSDSLab-NWB-metadata/tree/main/auditory/yaml/stimulus)) are actually useful for HTK processing and which ones are no longer relevant?

Example file that we were looking at: `wn2.yaml`

```yaml
name: wn
2type: discrete
mark_offset: 0.25
mark_threshold: 0.3
mark_sampling_rate: 12207.03125
nsamples: 60
duration: 0.1
stim_values: np.ones(60)
baseline_start: 0.3
baseline_end: 0.5
first_mark: 0.0
luigi_cls: WhiteNoiseAnalysis
tokenizer: wn_tokenize
````

**Comment by VBaratham** [comment]
I believe these are the only ones needed:

mark_offset: 0.25

mark_sampling_rate: 12207.03125

**Comment by jihyunbak** [comment]
Update: we are actually using most of the stimulus metadata items. For the `wn2.yaml` example above, these fields are being used:

```yaml
name: wn2
type: discrete
mark_offset: 0.25
mark_threshold: 0.3
mark_sampling_rate: 12207.03125
nsamples: 60
duration: 0.1
baseline_start: 0.3
baseline_end: 0.5
first_mark: 0.0
```

whereas these are no longer used.

```yaml
# stim_values: np.ones(60)
# luigi_cls: WhiteNoiseAnalysis
# tokenizer: wn_tokenize
```

Closing this issue with this note.
