### ISSUE TITLE
Number of stim onsets error in TIMIT tokenizer

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#94]
Running `python -sv test_catscan.py` with `RESAMPLE_DATA=False`, all passing except TIMIT block (number of stim onsets mismatch)

```python
==================================== short test summary info =====================================
FAILED test_catscan.py::test_nwb_builder[RVG16_B08] - AssertionError: Incorrect number of stimu...
====================== 1 failed, 11 passed, 1 warning in 339.06s (0:05:39) =======================
```

This is the full error message, and it is coming from TIMIT tokenizer around L36:

> AssertionError: Incorrect number of stimulus onsets found. Expected 998, found 637. Perhaps you are not using the correct tokenizer?

Quite a large discrepancy (998 vs 637) ...

**Comment by jihyunbak** [comment]
Hmm … could this be because this recorded_mark in this block was incomplete (i.e., the timit998 stimulus was not played to the end)? @jthermiz 

FYI, this is the content of `RVG16_B08.yaml`:

```yaml
animal_description: Charles River
animal_name: RVG16
animal_number: '16'
block_id: '8'
clean_block: '0'
ecog: '1'
ecog_acq: TDT PZM5
ecog_lat_loc: '1'
ecog_post_loc: '3'
ecog_serial: R42/R43
ecog_type: ecog128
experiment_description: This is an acute rat experiment. Auditory stimuli are played
  to an anesthsized rat and electrophysiological measurements are made auditory cortex
experimenter: Vanessa Gutierrez
genotype: Wild type
institution: Lawrence Berkeley National Lab
lab: Bouchard Lab
notes: FAIL Pz5 died
pharmacology: Anesthesized with Ketamine (90 mg/kg induction and 55 mg/kg maintence)
  and Xyzaline (10 mg/kg induction and 5 mg/kg maintence)
poly: '1'
poly_acq: TDT PZM5
poly_ap_loc: '13'
poly_dev_loc: '6'
poly_serial: '5500'
poly_type: camb64
procedure_date: '2021-05-25 00:00:00'
procedure_time: 08:40:00
sex: M
species: Sprague Dawley
stim_response: Bad
stimulus: Timit998
surgery: Right temporal lobe craniotomy w/ durotomy
surgery_notes: Clean window. minimal damage to surface
surgery_outcome: Ok
weight: '466'
```
